java_library(
    name="FormatException",
    srcs=["FormatException.java"],
    visibility=["//visibility:public"],
    deps=[":ReaderException"]
)

java_library(
    name="NotFoundException",
    srcs=["NotFoundException.java"],
    visibility=["//visibility:public"],
    deps=[":ReaderException"]
)


java_library(
    name="ReaderException",
    srcs=["ReaderException.java"],
)

java_library(
    name="ResultPoint",
    srcs=["ResultPoint.java"],
    visibility=["//visibility:public"],
    deps=["//src/peergos/shared/zxing/common/detector:MathUtils"]
)
