java_library(
    name = "Crypto",
    srcs = ["Crypto.java"],
    visibility = ["//visibility:public"],
    deps = [],
)

java_library(
    name = "CryptreeCache",
    srcs = ["CryptreeCache.java"],
    visibility = ["//visibility:public"],
    deps = [],
)

java_library(
    name = "MaybeMultihash",
    srcs = ["MaybeMultihash.java"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/peergos/shared/cbor:Cbor",
        "//src/peergos/shared/io/ipfs/cid:Cid",
        "//src/peergos/shared/io/ipfs/multihash:Multihash",
    ],
)

java_library(
    name = "NetworkAccess",
    srcs = ["NetworkAccess.java"],
    visibility = ["//visibility:public"],
    deps = [],
)