java_library(
    name="Curve25519",
    srcs=["Curve25519.java"],
    deps=[
        "//src/peergos/shared/crypto/random:JSNaCl",
    ],
)

java_library(
    name="Ed25519",
    srcs=["Ed25519.java"],
    deps=[
        "//src/peergos/shared/crypto/random:JSNaCl",
    ],
)
