
java_library(
    name="encoder",
    srcs=glob(["*.java"]),
    deps=[
        "//src/peergos/shared/zxing:EncodeHintType",
        # "//src/peergos/shared/zxing:FormatException",
        # "//src/peergos/shared/zxing:NotFoundException",
        # "//src/peergos/shared/zxing:ResultPoint",
        # "//src/peergos/shared/zxing:ResultPointCallback",
        # "//src/peergos/shared/zxing/common:BitMatrix",
        # "//src/peergos/shared/zxing/common:DetectorResult",
        # "//src/peergos/shared/zxing/common:GridSampler",
        # "//src/peergos/shared/zxing/common:PerspectiveTransform",
        # "//src/peergos/shared/zxing/common/detector:MathUtils",
        "//src/peergos/shared/zxing/qrcode/decoder:decoder",
    ]
)
