java_import(
    name = "gwt-api-checker",
    jars = ["gwt-api-checker.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gwt-codeserver",
    jars = ["gwt-codeserver.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gwt-dev",
    jars = ["gwt-dev.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gwt-servlet-deps",
    jars = ["gwt-servlet-deps.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gwt-servlet",
    jars = ["gwt-servlet.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "gwt-user",
    jars = ["gwt-user.jar"],
    visibility = ["//visibility:public"],
)
