java_import(
    name = "lib",
    jars = glob(["*.jar"]),
    visibility = ["//visibility:public"],
)

java_import(
    name = "HikariCP",
    jars = ["HikariCP-3.4.2.jar"],
)

java_import(
    name = "jain-sdp",
    jars = ["jain-sdp.jar"],
)

java_import(
    name = "jline",
    jars = ["jline-3.12.1.jar"],
)

java_import(
    name = "jnr-fuse",
    jars = ["jnr-fuse-0.3-all.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "postgresql",
    jars = ["postgresql-42.2.8.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "simpleclient",
    jars = ["simpleclient-0.8.0.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "simpleclient_common",
    jars = ["simpleclient_common-0.8.0.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "simpleclient_httpserver",
    jars = ["simpleclient_httpserver-0.8.0.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "slf4j-api",
    jars = ["slf4j-api-1.7.30.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "slf4j-nop",
    jars = ["slf4j-nop-1.7.30.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "sqlite-jdbc",
    jars = ["sqlite-jdbc-3.30.1.jar"],
    visibility = ["//visibility:public"],
)

java_import(
    name = "weupnp",
    jars = ["weupnp-0.1.2-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],
)
