java_library(
    name="Cbor",
    srcs=["CborObject.java", "Cborable.java",
          "CborConstants.java", "CborDecoder.java", "CborEncoder.java", "CborType.java"],
    deps=[
        "//src/peergos/shared/io/ipfs/multihash:Multihash",
        "//src/peergos/shared/io/ipfs/cid:Cid",
    ]
)
