java_import(
    name = "gwt-user",
    jars = ["gwt-user.jar"],
    visibility = ["//visibility:public"],
)
java_import(
    name = "hamcrest-core",
    jars = ["hamcrest-core-1.3.jar"],
    visibility = ["//visibility:public"],
)
java_import(
    name = "junit",
    jars = ["junit-4.11.jar"],
    visibility = ["//visibility:public"],
)